version: '3'

services:
  devops-springboot-container:
    image: devops-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/devops-springboot-container
    ports:
      - "8080-8100:8080"
